version: "3.9"
services:
  py3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/home/jovyan/work
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - /Users/tanakatomo/Documents/work/study/2021/kaggle/GM:/home/jovyan/work
